runs-on: ubuntu-latest
steps:
- run: mkdir packages
- uses: actions/checkout@master
- uses: nuget/setup-nuget@v1
  with:
    nuget-version: '5.x'
- run: nuget install DHI.DFS 19.0.0 -OutputDirectory packages -Source "https://api.nuget.org/v3/index.json"
- run: nuget install DHI.Projections 19.0.0 -OutputDirectory packages -Source "https://api.nuget.org/v3/index.json"
- run: nuget install DHI.MikeCore.Linux.rhel7 19.0.0 -OutputDirectory packages