name: Build package
on:
  push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
        
    steps:
    - name: Create packages directory
      run: mkdir packages
    - uses: actions/checkout@v2
    - name: Get nuget packages
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Install nuget packages
      run: |
       nuget install DHI.DFS -OutputDirectory packages -Source "https://api.nuget.org/v3/index.json"
       nuget install DHI.Projections -OutputDirectory packages -Source "https://api.nuget.org/v3/index.json"
       # unlisted package nuget install DHI.MikeCore.Linux.rhel7 -OutputDirectory packages -Source "https://api.nuget.org/v3/index.json"
    
    - name: Install packages into directory
      shell: cmd
      run: .\InstallPackages.bat
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Install mikecore-python
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pytest
