name: Test Linux

on:
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.12]

    steps:
      - uses: actions/checkout@v2
      - run: mkdir packages
      - uses: actions/checkout@v2
      - name: Get nuget packages
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: pwd
      - run: ls -l
      - name: Install nuget packages
        run: |
          nuget install DHI.MikeCore.Linux.rhel7 -Version 20.0.0 -OutputDirectory packages
      - run: mkdir -p mikecore/bin/linux
      - run: cp -r packages/DHI.MikeCore.Linux.rhel7.20.0.0/runtimes/linux-x64/native/* mikecore/bin/linux
      - run: sudo apt-get install patchelf
      - run: |
         patchelf --set-rpath '$ORIGIN' mikecore/bin/linux/libufs.so 
         patchelf --set-rpath '$ORIGIN' mikecore/bin/linux/libeum.so
         patchelf --set-rpath '$ORIGIN' mikecore/bin/linux/libMzCart.so
         patchelf --set-rpath '$ORIGIN' mikecore/bin/linux/libpfs2004.so
         patchelf --set-rpath '$ORIGIN' mikecore/bin/linux/libxerces-c-3.1.so
         

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        
      - name: Install mikecore-python
        run: pip install .
      - name: Test with pytest
        run: pytest
